//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavWebServiceDemo.Forms.NavJobListService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", ConfigurationName="NavJobListService.Job_List_Port")]
    public interface Job_List_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NavWebServiceDemo.Forms.NavJobListService.Read_Result Read(NavWebServiceDemo.Forms.NavJobListService.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.Read_Result> ReadAsync(NavWebServiceDemo.Forms.NavJobListService.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NavWebServiceDemo.Forms.NavJobListService.ReadByRecId_Result ReadByRecId(NavWebServiceDemo.Forms.NavJobListService.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.ReadByRecId_Result> ReadByRecIdAsync(NavWebServiceDemo.Forms.NavJobListService.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NavWebServiceDemo.Forms.NavJobListService.ReadMultiple_Result ReadMultiple(NavWebServiceDemo.Forms.NavJobListService.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.ReadMultiple_Result> ReadMultipleAsync(NavWebServiceDemo.Forms.NavJobListService.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NavWebServiceDemo.Forms.NavJobListService.IsUpdated_Result IsUpdated(NavWebServiceDemo.Forms.NavJobListService.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.IsUpdated_Result> IsUpdatedAsync(NavWebServiceDemo.Forms.NavJobListService.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey_Result GetRecIdFromKey(NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NavWebServiceDemo.Forms.NavJobListService.Create_Result Create(NavWebServiceDemo.Forms.NavJobListService.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.Create_Result> CreateAsync(NavWebServiceDemo.Forms.NavJobListService.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NavWebServiceDemo.Forms.NavJobListService.CreateMultiple_Result CreateMultiple(NavWebServiceDemo.Forms.NavJobListService.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.CreateMultiple_Result> CreateMultipleAsync(NavWebServiceDemo.Forms.NavJobListService.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NavWebServiceDemo.Forms.NavJobListService.Update_Result Update(NavWebServiceDemo.Forms.NavJobListService.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.Update_Result> UpdateAsync(NavWebServiceDemo.Forms.NavJobListService.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NavWebServiceDemo.Forms.NavJobListService.UpdateMultiple_Result UpdateMultiple(NavWebServiceDemo.Forms.NavJobListService.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.UpdateMultiple_Result> UpdateMultipleAsync(NavWebServiceDemo.Forms.NavJobListService.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NavWebServiceDemo.Forms.NavJobListService.Delete_Result Delete(NavWebServiceDemo.Forms.NavJobListService.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/job_list:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.Delete_Result> DeleteAsync(NavWebServiceDemo.Forms.NavJobListService.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list")]
    public partial class Job_List : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string noField;
        
        private string descriptionField;
        
        private string description_2Field;
        
        private string bill_to_Customer_NoField;
        
        private System.DateTime creation_DateField;
        
        private bool creation_DateFieldSpecified;
        
        private System.DateTime starting_DateField;
        
        private bool starting_DateFieldSpecified;
        
        private System.DateTime ending_DateField;
        
        private bool ending_DateFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private string person_ResponsibleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description_2 {
            get {
                return this.description_2Field;
            }
            set {
                this.description_2Field = value;
                this.RaisePropertyChanged("Description_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Bill_to_Customer_No {
            get {
                return this.bill_to_Customer_NoField;
            }
            set {
                this.bill_to_Customer_NoField = value;
                this.RaisePropertyChanged("Bill_to_Customer_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime Creation_Date {
            get {
                return this.creation_DateField;
            }
            set {
                this.creation_DateField = value;
                this.RaisePropertyChanged("Creation_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Creation_DateSpecified {
            get {
                return this.creation_DateFieldSpecified;
            }
            set {
                this.creation_DateFieldSpecified = value;
                this.RaisePropertyChanged("Creation_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime Starting_Date {
            get {
                return this.starting_DateField;
            }
            set {
                this.starting_DateField = value;
                this.RaisePropertyChanged("Starting_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Starting_DateSpecified {
            get {
                return this.starting_DateFieldSpecified;
            }
            set {
                this.starting_DateFieldSpecified = value;
                this.RaisePropertyChanged("Starting_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime Ending_Date {
            get {
                return this.ending_DateField;
            }
            set {
                this.ending_DateField = value;
                this.RaisePropertyChanged("Ending_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Ending_DateSpecified {
            get {
                return this.ending_DateFieldSpecified;
            }
            set {
                this.ending_DateFieldSpecified = value;
                this.RaisePropertyChanged("Ending_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("StatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Person_Responsible {
            get {
                return this.person_ResponsibleField;
            }
            set {
                this.person_ResponsibleField = value;
                this.RaisePropertyChanged("Person_Responsible");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list")]
    public enum Status {
        
        /// <remarks/>
        Planning,
        
        /// <remarks/>
        Quote,
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Completed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list")]
    public partial class Job_List_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Job_List_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Job_List_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list")]
    public enum Job_List_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Description_2,
        
        /// <remarks/>
        Bill_to_Customer_No,
        
        /// <remarks/>
        Creation_Date,
        
        /// <remarks/>
        Starting_Date,
        
        /// <remarks/>
        Ending_Date,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Person_Responsible,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public string No;
        
        public Read() {
        }
        
        public Read(string No) {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List;
        
        public Read_Result() {
        }
        
        public Read_Result(NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List) {
            this.Job_List = Job_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List) {
            this.Job_List = Job_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(NavWebServiceDemo.Forms.NavJobListService.Job_List_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(NavWebServiceDemo.Forms.NavJobListService.Job_List[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List;
        
        public Create() {
        }
        
        public Create(NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List) {
            this.Job_List = Job_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List;
        
        public Create_Result() {
        }
        
        public Create_Result(NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List) {
            this.Job_List = Job_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List[] Job_List_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(NavWebServiceDemo.Forms.NavJobListService.Job_List[] Job_List_List) {
            this.Job_List_List = Job_List_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List[] Job_List_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(NavWebServiceDemo.Forms.NavJobListService.Job_List[] Job_List_List) {
            this.Job_List_List = Job_List_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List;
        
        public Update() {
        }
        
        public Update(NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List) {
            this.Job_List = Job_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List;
        
        public Update_Result() {
        }
        
        public Update_Result(NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List) {
            this.Job_List = Job_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List[] Job_List_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(NavWebServiceDemo.Forms.NavJobListService.Job_List[] Job_List_List) {
            this.Job_List_List = Job_List_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NavWebServiceDemo.Forms.NavJobListService.Job_List[] Job_List_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(NavWebServiceDemo.Forms.NavJobListService.Job_List[] Job_List_List) {
            this.Job_List_List = Job_List_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/job_list", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/job_list", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Job_List_PortChannel : NavWebServiceDemo.Forms.NavJobListService.Job_List_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Job_List_PortClient : System.ServiceModel.ClientBase<NavWebServiceDemo.Forms.NavJobListService.Job_List_Port>, NavWebServiceDemo.Forms.NavJobListService.Job_List_Port {
        
        public Job_List_PortClient() {
        }
        
        public Job_List_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Job_List_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Job_List_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Job_List_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWebServiceDemo.Forms.NavJobListService.Read_Result NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.Read(NavWebServiceDemo.Forms.NavJobListService.Read request) {
            return base.Channel.Read(request);
        }
        
        public NavWebServiceDemo.Forms.NavJobListService.Job_List Read(string No) {
            NavWebServiceDemo.Forms.NavJobListService.Read inValue = new NavWebServiceDemo.Forms.NavJobListService.Read();
            inValue.No = No;
            NavWebServiceDemo.Forms.NavJobListService.Read_Result retVal = ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).Read(inValue);
            return retVal.Job_List;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.Read_Result> NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.ReadAsync(NavWebServiceDemo.Forms.NavJobListService.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.Read_Result> ReadAsync(string No) {
            NavWebServiceDemo.Forms.NavJobListService.Read inValue = new NavWebServiceDemo.Forms.NavJobListService.Read();
            inValue.No = No;
            return ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWebServiceDemo.Forms.NavJobListService.ReadByRecId_Result NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.ReadByRecId(NavWebServiceDemo.Forms.NavJobListService.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public NavWebServiceDemo.Forms.NavJobListService.Job_List ReadByRecId(string recId) {
            NavWebServiceDemo.Forms.NavJobListService.ReadByRecId inValue = new NavWebServiceDemo.Forms.NavJobListService.ReadByRecId();
            inValue.recId = recId;
            NavWebServiceDemo.Forms.NavJobListService.ReadByRecId_Result retVal = ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).ReadByRecId(inValue);
            return retVal.Job_List;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.ReadByRecId_Result> NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.ReadByRecIdAsync(NavWebServiceDemo.Forms.NavJobListService.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            NavWebServiceDemo.Forms.NavJobListService.ReadByRecId inValue = new NavWebServiceDemo.Forms.NavJobListService.ReadByRecId();
            inValue.recId = recId;
            return ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWebServiceDemo.Forms.NavJobListService.ReadMultiple_Result NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.ReadMultiple(NavWebServiceDemo.Forms.NavJobListService.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public NavWebServiceDemo.Forms.NavJobListService.Job_List[] ReadMultiple(NavWebServiceDemo.Forms.NavJobListService.Job_List_Filter[] filter, string bookmarkKey, int setSize) {
            NavWebServiceDemo.Forms.NavJobListService.ReadMultiple inValue = new NavWebServiceDemo.Forms.NavJobListService.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            NavWebServiceDemo.Forms.NavJobListService.ReadMultiple_Result retVal = ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.ReadMultiple_Result> NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.ReadMultipleAsync(NavWebServiceDemo.Forms.NavJobListService.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.ReadMultiple_Result> ReadMultipleAsync(NavWebServiceDemo.Forms.NavJobListService.Job_List_Filter[] filter, string bookmarkKey, int setSize) {
            NavWebServiceDemo.Forms.NavJobListService.ReadMultiple inValue = new NavWebServiceDemo.Forms.NavJobListService.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWebServiceDemo.Forms.NavJobListService.IsUpdated_Result NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.IsUpdated(NavWebServiceDemo.Forms.NavJobListService.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            NavWebServiceDemo.Forms.NavJobListService.IsUpdated inValue = new NavWebServiceDemo.Forms.NavJobListService.IsUpdated();
            inValue.Key = Key;
            NavWebServiceDemo.Forms.NavJobListService.IsUpdated_Result retVal = ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.IsUpdated_Result> NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.IsUpdatedAsync(NavWebServiceDemo.Forms.NavJobListService.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.IsUpdated_Result> IsUpdatedAsync(string Key) {
            NavWebServiceDemo.Forms.NavJobListService.IsUpdated inValue = new NavWebServiceDemo.Forms.NavJobListService.IsUpdated();
            inValue.Key = Key;
            return ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey_Result NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.GetRecIdFromKey(NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey inValue = new NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey();
            inValue.Key = Key;
            NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey_Result retVal = ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey_Result> NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.GetRecIdFromKeyAsync(NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey inValue = new NavWebServiceDemo.Forms.NavJobListService.GetRecIdFromKey();
            inValue.Key = Key;
            return ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWebServiceDemo.Forms.NavJobListService.Create_Result NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.Create(NavWebServiceDemo.Forms.NavJobListService.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List) {
            NavWebServiceDemo.Forms.NavJobListService.Create inValue = new NavWebServiceDemo.Forms.NavJobListService.Create();
            inValue.Job_List = Job_List;
            NavWebServiceDemo.Forms.NavJobListService.Create_Result retVal = ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).Create(inValue);
            Job_List = retVal.Job_List;
        }
        
        public System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.Create_Result> CreateAsync(NavWebServiceDemo.Forms.NavJobListService.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWebServiceDemo.Forms.NavJobListService.CreateMultiple_Result NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.CreateMultiple(NavWebServiceDemo.Forms.NavJobListService.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref NavWebServiceDemo.Forms.NavJobListService.Job_List[] Job_List_List) {
            NavWebServiceDemo.Forms.NavJobListService.CreateMultiple inValue = new NavWebServiceDemo.Forms.NavJobListService.CreateMultiple();
            inValue.Job_List_List = Job_List_List;
            NavWebServiceDemo.Forms.NavJobListService.CreateMultiple_Result retVal = ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).CreateMultiple(inValue);
            Job_List_List = retVal.Job_List_List;
        }
        
        public System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.CreateMultiple_Result> CreateMultipleAsync(NavWebServiceDemo.Forms.NavJobListService.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWebServiceDemo.Forms.NavJobListService.Update_Result NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.Update(NavWebServiceDemo.Forms.NavJobListService.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref NavWebServiceDemo.Forms.NavJobListService.Job_List Job_List) {
            NavWebServiceDemo.Forms.NavJobListService.Update inValue = new NavWebServiceDemo.Forms.NavJobListService.Update();
            inValue.Job_List = Job_List;
            NavWebServiceDemo.Forms.NavJobListService.Update_Result retVal = ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).Update(inValue);
            Job_List = retVal.Job_List;
        }
        
        public System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.Update_Result> UpdateAsync(NavWebServiceDemo.Forms.NavJobListService.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWebServiceDemo.Forms.NavJobListService.UpdateMultiple_Result NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.UpdateMultiple(NavWebServiceDemo.Forms.NavJobListService.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref NavWebServiceDemo.Forms.NavJobListService.Job_List[] Job_List_List) {
            NavWebServiceDemo.Forms.NavJobListService.UpdateMultiple inValue = new NavWebServiceDemo.Forms.NavJobListService.UpdateMultiple();
            inValue.Job_List_List = Job_List_List;
            NavWebServiceDemo.Forms.NavJobListService.UpdateMultiple_Result retVal = ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).UpdateMultiple(inValue);
            Job_List_List = retVal.Job_List_List;
        }
        
        public System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.UpdateMultiple_Result> UpdateMultipleAsync(NavWebServiceDemo.Forms.NavJobListService.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavWebServiceDemo.Forms.NavJobListService.Delete_Result NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.Delete(NavWebServiceDemo.Forms.NavJobListService.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            NavWebServiceDemo.Forms.NavJobListService.Delete inValue = new NavWebServiceDemo.Forms.NavJobListService.Delete();
            inValue.Key = Key;
            NavWebServiceDemo.Forms.NavJobListService.Delete_Result retVal = ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.Delete_Result> NavWebServiceDemo.Forms.NavJobListService.Job_List_Port.DeleteAsync(NavWebServiceDemo.Forms.NavJobListService.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavWebServiceDemo.Forms.NavJobListService.Delete_Result> DeleteAsync(string Key) {
            NavWebServiceDemo.Forms.NavJobListService.Delete inValue = new NavWebServiceDemo.Forms.NavJobListService.Delete();
            inValue.Key = Key;
            return ((NavWebServiceDemo.Forms.NavJobListService.Job_List_Port)(this)).DeleteAsync(inValue);
        }
    }
}
